# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  USE_BSPM: "true"
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  lucode2-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap
        run: |
          curl -OLs https://eddelbuettel.github.io/r-ci/run.sh
          chmod 0755 run.sh
          ./run.sh bootstrap

      - name: Use pik-piam r-universe
        run: echo 'options(repos = c(universe = "https://pik-piam.r-universe.dev", CRAN = "https://cloud.r-project.org"))' > .Rprofile

      - name: Dependencies
        run: |
          ./run.sh install_all
          ./run.sh install_r lucode2

      - name: Verify ValidationKey
        run: lucode2:::validkey(stopIfInvalid = TRUE)
        shell: Rscript {0}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Checks, Tests, Linter
        run: |
          options(crayon.enabled = TRUE)
          lucode2::check()
        shell: Rscript {0}

      - name: Coverage
        run: ./run.sh coverage

