# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: lucode2-check

jobs:
  lucode2-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: release
          install-r: false
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Use pik-piam r-universe
        shell: bash
        run: echo 'options(repos = c(universe = "https://pik-piam.r-universe.dev", CRAN = "https://cloud.r-project.org"))' > .Rprofile

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            lucode2
            covr

      - name: Validation key
        run: if(!lucode2:::validkey()$valid) stop("Invalid build key!")
        shell: Rscript {0}

      - name: Check
        run: |
          options(crayon.enabled = TRUE)
          lucode2::check()
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}
